"""Class encapsulating easy-to-use Unicode Emoji strings"""

class SimpleIcons:
    """Icons for use in web output from https://emojiguide.org/"""

    NOTEBOOK = "📒"
    DOCUMENT = "📄"
    PROPERTIES = "📝"
    FOLDER = "📁"
    OPEN_FOLDER = "📂"

    DIVIDE = "➗"
    GEAR = "⚙️"
    INFO = "ℹ️"
    LEFTRIGHT_ARROW = "↔️"
    MAGNIFIER = "🔎"
    NUMBERS = "🔢"
    QUESTION = "❓"
    RIGHT_ARROW = "➡️"
    SCISSORS = "✂️"
    TOOLBOX = "🧰"
    WRENCH = "🔧"

    BELL = "🔔"
    NO_BELL = "🔕"
    BULB = "💡"
    CONSTRUCTION = "🚧"
    CONTROLS = "🎛️"
    DATE = "📅"
    HOURGLASS = "⏳"
    STOP_WATCH = "⏱️"
    WATCH = "⌚"

    CAMERA = "📷"
    CLAPPER = "🎬"
    FILM = "🎞️"
    MICROPHONE = "🎤"
    MOVIE = "🎥"
    PICTURE = "🖼️"
    TELEVISION = "📺"

    OK_HAND = "👌"
    FINGERS_CROSSED = "🤞"
    FIST = "🤜"
    THUMBS_DOWN = "👎"
    THUMBS_UP = "👍"

    COPYRIGHT = "©️"
    NO_ENTRY = "⛔"
    PROHIBITED = "🚫"
    WARNING = "⚠️"

    BALLOON = "🎈"
    BOMB = "💣"
    CHERRY_BLOSSOM = "🌸"
    EGGPLANT = "🍆"
    GHOST = "👻"
    HAMMER = "🔨"
    HEART = "❤️"
    TWO_HEARTS = "💕"
    MAGIC_WAND = "🪄"
    MICROSCOPE = "🔬"
    ROCKET = "🚀"
    SOAP = "🧼"
    STILL = "⚗️"
    SWEAT = "💦"
    GEMSTONE = "💎"
    LABCOAT = "🥼"
