"""Class encapsulating easy-to-use Unicode Emoji strings"""

class SimpleIcons:
    """Icons for use in web output from https://emojiguide.org/"""
    NOTEBOOK = "📒"
    DOCUMENT = "📄"
    PROPERTIES = "📝"
    FOLDER = "📁"
    OPEN_FOLDER = "📂"

    DIVIDE = "➗"
    GEAR = "⚙️"
    INFO = "ℹ️"
    LEFTRIGHT_ARROW = "↔️"
    MAGNIFIER = "🔎"
    NUMBERS = "🔢"
    QUESTION = "❓"
    RIGHT_ARROW = "➡️"
    SCISSORS = "✂️"
    TOOLBOX = "🧰"
    WRENCH = "🔧"

    BELL = "🔔"
    NO_BELL = "🔕"
    BULB = "💡"
    CONSTRUCTION = "🚧"
    CONTROLS = "🎛️"
    DATE = "📅"
    HOURGLASS = "⏳"
    SLIDER = "🎚️"
    STOP_WATCH = "⏱️"
    WATCH = "⌚"

    CAMERA = "📷"
    CASSETTE = "📼"
    CLAPPER = "🎬"
    FILM = "🎞️"
    MICROPHONE = "🎤"
    MOVIE = "🎥"
    PICTURE = "🖼️"
    PLAY = "▶️"
    PROJECTOR = "📽️"
    TELEVISION = "📺"
    THEATER = "🎭"
    VIDEO_CAMERA = "📹"

    OK_HAND = "👌"
    FINGERS_CROSSED = "🤞"
    FIST = "🤜"
    THUMBS_DOWN = "👎"
    THUMBS_UP = "👍"

    COPYRIGHT = "©️"
    NO_ENTRY = "⛔"
    PROHIBITED = "🚫"
    WARNING = "⚠️"

    BALLOON = "🎈"
    BOMB = "💣"
    CHERRY_BLOSSOM = "🌸"
    COOL = "🆒"
    EGGPLANT = "🍆"
    GEMSTONE = "💎"
    GHOST = "👻"
    GIFT = "🎁"
    GLOBE = "🌎"
    HAMMER = "🔨"
    HEART = "❤️"
    INCREASING = "📈"
    LABCOAT = "🥼"
    MAGIC_WAND = "🪄"
    MICROSCOPE = "🔬"
    PACKAGE = "📦"
    ROBOT = "🤖"
    ROCKET = "🚀"
    SCROLL = "📜"
    SOAP = "🧼"
    STILL = "⚗️"
    SWEAT = "💦"
    TWO_HEARTS = "💕"

    # shared symbol definitions
    TIPS_SYMBOL = INFO
    SLOW_SYMBOL = WATCH
    PROP_SYMBOL = PROPERTIES
    WISH_SYMBOL = FINGERS_CROSSED
    CONV_SYMBOL = STILL
