directories:
  working: "./temp"
  output_interpolation: "./output/interpolation"
  output_inflation: "./output/inflation"
  output_search: "./output/search"
model: "./pretrained_models/pretrained_VFIformer/net_220.pth"
gpu_ids: "0"
auto_launch_browser: True
server_port: 7862
server_name: "0.0.0.0"
interpolate_settings:
  gif_duration: 3000
  create_gif: True
  create_zip: True
  create_txt: True
user_interface:
  theme: "default"
  css_file: "webui.css"
